---     
# help ansible-doc yum    
- name: Playbook for question3
  hosts: all
  tasks:
    - name: install the packages
      yum:
        name:
         - mariadb
         - php
        state: present
      when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']

    - name: install the RPM development tool package group
      yum:
        name: "@RPM Development tools"
        state: present
      when: inventory_hostname in groups['dev']
        
    - name: update all packages
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']